# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Sample Run and Dependabot Auto-merge
on:
  push:
  pull_request_target:
    branches: [ master ]

permissions:
  id-token: write
  contents: write

jobs:
  sample-run:
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
#        dotnet-version: [ '6.0.x', '8.0.x' ]
#        jdk-version: [ "8", "11", "17", "21", "24" ]
        dotnet-version: [ '6.0.x', '7.0.x', '8.0.x' ]
        jdk-version: [ "8", "24" ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - name: Checkout working directory
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::751999266872:role/GitHubWorkflows
          role-session-name: myGitHubActions

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'corretto'

      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Test (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet build --no-restore
          dotnet test --no-build --os linux-x64

      - name: Build and Test (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          dotnet build --no-restore
          dotnet test --no-build --os osx-x64

      - name: Build and Test (windows)
        if: matrix.os == 'windows-latest'
        run: |
          dotnet build --no-restore
          dotnet test --no-build --os win-x64
